import Anthropic from '@anthropic-ai/sdk';

import type { ReviewConfig, ReviewResult } from '../model/types';

const REVIEW_SYSTEM_PROMPT = `You are an independent code reviewer for the MIXTI auto-recovery system. Your job is to review an automated fix that was generated by a SEPARATE AI agent.

You are NOT the author of this fix. Evaluate it critically and independently.

Review criteria:
1. Security: Does the fix introduce any security vulnerabilities?
2. Validation weakening: Does the fix disable, skip, or weaken any existing validation, authentication, or authorization checks?
3. Incident path coverage: Does the fix actually address the files/paths where the original incident occurred?
4. Regression coverage: Are there test changes that cover the fix? Could this break existing behavior?
5. Correctness: Is the fix logically correct and minimal?

Respond ONLY with a JSON object matching this schema:
{
  "isApproved": boolean,
  "isIncidentPathCovered": boolean,
  "isRegressionCovered": boolean,
  "isValidationWeakened": boolean,
  "findings": string[]
}

- isApproved: true only if the fix is safe, correct, and addresses the incident
- isIncidentPathCovered: true if the changed files relate to the incident paths
- isRegressionCovered: true if test coverage exists for the changes
- isValidationWeakened: true if any validation/auth/security checks are weakened
- findings: array of review observations (empty if no issues)`;

const performReview = async (config: ReviewConfig): Promise<ReviewResult> => {
  const anthropic = new Anthropic({ apiKey: config.anthropicApiKey });

  const prompt = [
    '## Incident Context',
    `- Fingerprint: ${config.incidentFingerprint}`,
    `- Category: ${config.incidentCategory}`,
    `- Fix description: ${config.fixDescription}`,
    '',
    '## Changed Files',
    config.changedFiles.map((f) => `- ${f}`).join('\n'),
    '',
    '## Diff',
    '```',
    config.diff,
    '```',
  ].join('\n');

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: config.maxTokens,
    system: REVIEW_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: prompt }],
  });

  const text = response.content
    .filter((block): block is Anthropic.TextBlock => block.type === 'text')
    .map((block) => block.text)
    .join('');

  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    return {
      isApproved: false,
      isIncidentPathCovered: false,
      isRegressionCovered: false,
      isValidationWeakened: true,
      findings: ['Failed to parse review response'],
    };
  }

  try {
    const parsed = JSON.parse(jsonMatch[0]) as ReviewResult;
    return {
      isApproved: parsed.isApproved === true,
      isIncidentPathCovered: parsed.isIncidentPathCovered === true,
      isRegressionCovered: parsed.isRegressionCovered === true,
      isValidationWeakened: parsed.isValidationWeakened !== false,
      findings: Array.isArray(parsed.findings) ? parsed.findings : [],
    };
  } catch {
    return {
      isApproved: false,
      isIncidentPathCovered: false,
      isRegressionCovered: false,
      isValidationWeakened: true,
      findings: ['Failed to parse review JSON'],
    };
  }
};

export { performReview };
